services:
  shortener:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    command: ./url-shortener
    restart: always
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5443:5432"
    environment:
      - POSTGRES_DB=shortener
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

volumes:
  shortener:
  db:
