services:
  shortener:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
      - "4200:4200"
    depends_on:
      - clickhouse
      - db
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickhouse
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_config:/etc/clickhouse-server

  db:
    restart: always
    image: postgres:latest
    ports:
      - "5443:5432"
    environment:
      - POSTGRES_DB=shortener
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
volumes:
  db:
  shortener:
  clickhouse_data:
  clickhouse_config:
