services:
  shortener:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    env_file:
      ".env"
    command: ./url-shortener
    restart: always
volumes:
  shortener:
